#!/usr/bin/env python3
"""Render every icon resource of the `doksho` flavour from shiroikuma/icon/doksho-icon.svg.

The flavour source set overrides upstream's resources BY NAME, so every place upstream shows its
icon — launcher, splash, TTS notification layouts, file info, popup menus — shows ours without an
upstream file being edited:

  mipmap-anydpi-v26/icon_pdf_pro.xml      adaptive launcher icon (black ground, yellow line-art,
                                          monochrome layer for themed icons)
  mipmap-xxhdpi/icon_pdf_pro.png          legacy launcher raster (pre-API-26, <bitmap> users)
  drawable-xxhdpi/icon_pro_square.png     the About-page product icon
  drawable/ic_doksho_foreground.xml       the adaptive foreground (vector)
  drawable/ic_doksho_monochrome.xml       the themed-icon layer (vector)
  drawable/ic_notification_librera.xml    the status-bar small icon (white alpha mask)
  values/colors_doksho.xml                the icon ground colour
  shiroikuma/icon/doksho-icon-512.png     for the README / releases

Needs rsvg-convert and magick. Usage: python3 shiroikuma/icon/gen-icons.py
"""
import os
import re
import subprocess
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SVG = os.path.join(ROOT, "shiroikuma/icon/doksho-icon.svg")
RES = os.path.join(ROOT, "app/src/doksho/res")
YELLOW, BLACK = "#FFFF00", "#000000"
HEADER = "<!-- Generated by shiroikuma/icon/gen-icons.py from shiroikuma/icon/doksho-icon.svg — do not edit. -->"


def write(rel, text):
    path = os.path.join(RES, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write(text)
    print(f">>> {path}")


def main():
    svg = open(SVG, encoding="utf-8").read()
    groups = re.findall(r'<g transform="([^"]+)"', svg)
    ox, oy, k = map(float, re.match(r"translate\(([-\d.]+),([-\d.]+)\) scale\(([-\d.]+)\)", groups[0]).groups())
    th = float(re.match(r"translate\([-\d.]+,([-\d.]+)\)", groups[1]).group(1))
    paths = re.findall(r'<path d="([^"]+)"', svg)
    cw, ch = (108 - 2 * ox) / k, (108 - 2 * oy) / k

    def vector(color, size_dp, fill, viewport=108):
        """The mark as a VectorDrawable, its larger side `fill` units of the viewport, centred."""
        kk = fill / max(cw, ch)
        tx, ty = (viewport - cw * kk) / 2, (viewport - ch * kk) / 2
        body = "\n".join(f'            <path android:fillColor="{color}" android:fillType="evenOdd"\n'
                         f'                android:pathData="{p}" />' for p in paths)
        return f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size_dp}dp"
    android:height="{size_dp}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}">
    <group android:translateX="{tx:.4f}" android:translateY="{ty:.4f}"
        android:scaleX="{kk:.6f}" android:scaleY="{kk:.6f}">
        <group android:translateY="{th}" android:scaleX="0.1" android:scaleY="-0.1">
{body}
        </group>
    </group>
</vector>
'''

    mark = 108 * max(cw, ch) * k / 108          # the mark's larger side in the 108 viewport
    write("drawable/ic_doksho_foreground.xml", vector(YELLOW, 108, mark))
    write("drawable/ic_doksho_monochrome.xml", vector(BLACK, 108, mark))
    write("drawable/ic_notification_librera.xml", vector("#FFFFFF", 24, 104))
    write("values/colors_doksho.xml", f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}
<resources>
    <color name="doksho_icon_background">{BLACK}</color>
</resources>
''')
    write("mipmap-anydpi-v26/icon_pdf_pro.xml", f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/doksho_icon_background" />
    <foreground android:drawable="@drawable/ic_doksho_foreground" />
    <monochrome android:drawable="@drawable/ic_doksho_monochrome" />
</adaptive-icon>
''')

    with tempfile.TemporaryDirectory() as tmp:
        master = os.path.join(tmp, "master.png")
        subprocess.run(["rsvg-convert", "-w", "1024", "-h", "1024", SVG, "-o", master], check=True)

        def rounded(size, out):
            os.makedirs(os.path.dirname(out), exist_ok=True)
            r = int(size * 0.225)
            mask = os.path.join(tmp, "mask.png")
            subprocess.run(["magick", "-size", f"{size}x{size}", "xc:black", "-fill", "white", "-draw",
                            f"roundrectangle 0,0,{size - 1},{size - 1},{r},{r}", mask], check=True)
            subprocess.run(["magick", master, "-resize", f"{size}x{size}", mask, "-alpha", "off",
                            "-compose", "CopyOpacity", "-composite", out], check=True)
            print(f">>> {out}")

        rounded(144, os.path.join(RES, "mipmap-xxhdpi/icon_pdf_pro.png"))
        rounded(144, os.path.join(RES, "drawable-xxhdpi/icon_pro_square.png"))
        rounded(512, os.path.join(ROOT, "shiroikuma/icon/doksho-icon-512.png"))


if __name__ == "__main__":
    main()
