#!/usr/bin/env python3
"""Generate the 白い熊 読書 de-branding overrides for the `doksho` flavour.

1. Strings.
Every <string> in app/src/main/res/values*/strings*.xml whose value names Librera is re-emitted,
with the name replaced, into app/src/doksho/res/<same values dir>/strings_doksho.xml. Flavour
resources win over `main`, so upstream's 48 locale files stay untouched and a rebase never
conflicts on them. Re-run after every upstream sync (the upstream-new-version skill does); the
output is committed.

Kept as is: LibreraX (upstream's separate app — its mode is hidden in our build anyway), string
*names*, and words that merely contain the letters (Italian "libreria").

2. The licences page. app/src/main/assets/licenses.html opens with Librera's own header and
link; app/src/doksho/assets/licenses.html is the same page with our header on top, crediting
Librera Reader as the upstream (GPL-3.0) — the library list below stays upstream's, current.

Usage: python3 shiroikuma/debrand.py
"""
import glob
import os
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN = os.path.join(ROOT, "app/src/main/res")
OUT = os.path.join(ROOT, "app/src/doksho/res")
NAME = "白い熊 読書"
OUT_FILE = "strings_doksho.xml"

STRING = re.compile(r'(<string\b[^>]*>)(.*?)(</string>)', re.S)
# "Librera" as a word (not "LibreraX"), plus the Arabic transliteration one locale uses.
BRAND = re.compile(r'Librera(?!X)|ليبريرا')


def main():
    for old in glob.glob(os.path.join(OUT, "values*", OUT_FILE)):
        os.remove(old)
    total = files = 0
    for src in sorted(glob.glob(os.path.join(MAIN, "values*", "strings*.xml"))):
        text = open(src, encoding="utf-8").read()
        out = []
        for m in STRING.finditer(text):
            head, value, tail = m.groups()
            if 'name="librerax' in head or not BRAND.search(value):
                continue
            out.append(f"    {head}{BRAND.sub(NAME, value)}{tail}")
        if not out:
            continue
        values_dir = os.path.basename(os.path.dirname(src))
        dest_dir = os.path.join(OUT, values_dir)
        os.makedirs(dest_dir, exist_ok=True)
        dest = os.path.join(dest_dir, OUT_FILE)
        mode = "a" if os.path.exists(dest) else "w"
        with open(dest, mode, encoding="utf-8") as f:
            if mode == "w":
                f.write('<?xml version="1.0" encoding="utf-8"?>\n'
                        '<!-- Generated by shiroikuma/debrand.py from app/src/main/res — '
                        'do not edit. -->\n<resources>\n')
            f.write("\n".join(out) + "\n")
        total += len(out)
        files += 1
    for dest in glob.glob(os.path.join(OUT, "values*", OUT_FILE)):
        with open(dest, "a", encoding="utf-8") as f:
            f.write("</resources>\n")
    print(f">>> {total} strings in {files} source files → {OUT}/values*/{OUT_FILE}")


LICENSES_HEAD = re.compile(r'<h3>Librera Reader</h3>\s*<a href="https://librera\.mobi">https://librera\.mobi</a><br/>')
LICENSES_OURS = (
    '<h3>白い熊 読書</h3>\n'
    '<a href="https://github.com/ShiroiKuma0/shiroikuma-doksho">'
    'https://github.com/ShiroiKuma0/shiroikuma-doksho</a><br/>\n'
    'Based on <a href="https://github.com/foobnix/LibreraReader">Librera Reader</a> '
    '© Ivan Ivanenko, GPL-3.0.<br/>')


def licenses():
    src = os.path.join(ROOT, "app/src/main/assets/licenses.html")
    text = open(src, encoding="utf-8").read()
    new, n = LICENSES_HEAD.subn(LICENSES_OURS, text)
    if n != 1:
        raise SystemExit("licenses.html: upstream's header changed — update LICENSES_HEAD")
    dest = os.path.join(ROOT, "app/src/doksho/assets/licenses.html")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, "w", encoding="utf-8").write(new)
    print(f">>> {dest}")


if __name__ == "__main__":
    main()
    licenses()
